[WIP] Collapsible JSON component
markdoc/docs pull request #56
Opened 2022-05-16 17:41 UTC by matv-stripe

The JSON view in the sandbox would be easier to understand if 

- it was collapsible
- had a scroll container
- let you highlight parts of the source text and see where in the JSON view that source text comes from

This attempts the first part, but a WIP since I have not fixed all the styling.

2022-05-16 17:42 UTC, matv-stripe commented on components/ObjectDisplay.js
> +  return (
Thanks @ianjabour-stripe for the inspiration here!

But maybe a better solution here is use code mirror folding? - https://codemirror.net/demo/folding.html

2022-05-16 17:43 UTC, matv-stripe commented
cc @nkohari-stripe 

r? @mfix-stripe , WDYT of this approach?

2022-05-16 18:43 UTC, mfix-stripe requested changes
PTAL @matv-stripe

2022-05-16 18:43 UTC, mfix-stripe commented on components/Sandbox.js
> +          {/* {mode === 'ast' && (
Can we just delete this commented out code?

2022-05-16 18:43 UTC, mfix-stripe commented on components/Sandbox.js
> +          {mode === 'ast' && <ObjectDisplay data={ast} />}
Let's also use this for the `transform` mode directly above

2022-05-16 18:43 UTC, mfix-stripe commented on components/Sandbox.js
> +  const errors = React.useMemo(() => Markdoc.validate(ast, config), [
Why is your prettier different? ahah

2022-05-16 18:43 UTC, mfix-stripe commented on components/ObjectDisplay.js
> +        isArray={Array.isArray(data)}
Feels like you don't need this prop—can just be derived from `data`

2022-05-16 18:43 UTC, mfix-stripe commented on components/ObjectDisplay.js
> +        {!isRoot && <pre>{','}</pre>}
Do we need this `isRoot` thing?

2022-05-25 22:37 UTC, mfix-stripe commented
PTAL @matv-stripe!

2022-05-26 13:09 UTC, matv-stripe commented
I like it, thanks for fixing this up!

I think it might be cleaner if it defaulted to something like this instead of showing everything initially:
![image](https://user-images.githubusercontent.com/55463370/170493811-5b973598-5301-4d10-af88-a6d4158a3f99.png)

Maybe code folding might be an easier solution - but I am good with merging this because it is an improvement!

2022-05-26 13:10 UTC, matv-stripe commented
ptal @mfix-stripe , I cant approve this because its my branch 😆

2022-05-26 16:09 UTC, mfix-stripe approved these changes

2022-05-26 16:14 UTC, mfix-stripe commented
@matv-stripe thanks! How does this look: 
![image](https://user-images.githubusercontent.com/62121649/170529363-8b95c92d-025f-4a54-82d6-622411a2d0fb.png)

2022-05-26 16:36 UTC, matv-stripe commented
Its great! @mfix-stripe

2022-05-26 16:52 UTC, merged